### ISSUE TITLE
Sorting in the browser

### ISSUE THREAD

**Issue by winged** [freedomvote/freedomvote#4]
When comparing politician's answers with the "preferred" answers, it is possible to sort the results server-side. However, comparing politician's views with the visitor's views is not really possible to do efficiently via database query.

Therefore, instead of not sorting at all, we should sort the list in both cases in the browser instead.

**Comment by nicorikken** [comment]
I guess part of the issue is in updating the filtered results later on? Every filter or sort request would result in a server side request, taking the answers of the visitor, and again comparing the answers. Unless user sessions would also be cached on the server side, or the user comparison results are stored at the user side, indeed the sorting would involve the overhead of a SQL query.
What I take from this, is that eventually the comparison statistics should be stored at the user, per politician, per question category.
